#!/bin/bash
sudo apt update 
sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update 
sudo apt install python3.9
sudo su
update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1
update-alternatives --install /usr/bin/python3 python /usr/bin/python3.9 1
sudo apt-get update
sudo apt-get -y install python3-pip
pip3 install virtualenv
cd /home/ubuntu/klarrio
virtualenv venv1
source venv1/bin/activate
pip3 install -r requirements.txt